### ISSUE TITLE
ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")

### ISSUE THREAD

**Issue by radiocity** [danielguerra69/alpine-elasticsearch#2]
### Error
```bash
elasticsearch_1  | 2018-06-26 10:48:44,485 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
elasticsearch_1  |      at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
elasticsearch_1  |      at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
elasticsearch_1  |      at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
elasticsearch_1  |      at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
elasticsearch_1  |      at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
elasticsearch_1  |      at org.apache.logging.log4j.core.jmx.Server.register(Server.java:389)
elasticsearch_1  |      at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:167)
elasticsearch_1  |      at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
elasticsearch_1  |      at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:541)
elasticsearch_1  |      at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:258)
elasticsearch_1  |      at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:206)
elasticsearch_1  |      at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:220)
elasticsearch_1  |      at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:197)
elasticsearch_1  |      at org.elasticsearch.common.logging.LogConfigurator.configureStatusLogger(LogConfigurator.java:125)
elasticsearch_1  |      at org.elasticsearch.common.logging.LogConfigurator.configureWithoutConfig(LogConfigurator.java:67)
elasticsearch_1  |      at org.elasticsearch.cli.Command.main(Command.java:85)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)
elasticsearch_1  |
elasticsearch_1  | starts elasticsearch
elasticsearch_1  |
elasticsearch_1  | Option                Description
elasticsearch_1  | ------                -----------
elasticsearch_1  | -E <KeyValuePair>     Configure a setting
elasticsearch_1  | -V, --version         Prints elasticsearch version information and exits
elasticsearch_1  | -d, --daemonize       Starts Elasticsearch in the background
elasticsearch_1  | -h, --help            show help
elasticsearch_1  | -p, --pidfile <Path>  Creates a pid file in the specified path on start
elasticsearch_1  | -q, --quiet           Turns off standard ouput/error streams logging in console
elasticsearch_1  | -s, --silent          show minimal output
elasticsearch_1  | -v, --verbose         show verbose output
elasticsearch_1  | ERROR: Positional arguments not allowed, found [start]
docker_elasticsearch_1 exited with code 64

```
### docker-compose.yml
```yml
version: '3.3'
services:
  elasticsearch:
    image: danielguerra/alpine-elasticsearch:5.2.2
    volumes:
      - ./docker/userdata/elasticsearch:/usr/share/java/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - 'overlay'
```

**Comment by danielguerra69** [comment]
Should be changed to 
elasticsearch:
    image: danielguerra/alpine-elasticsearch
    volumes:
The same for kibana

**Comment by radiocity** [comment]
I need 5.2.2 elasticsearch version, not the latest.

**Comment by danielguerra69** [comment]
Look at my tags, I dont have it. The only 5.2.2 i have is 5.2.2-cluster. 5.2.2 is a really bad version ...

**Comment by danielguerra69** [comment]
You can use "elasticsearch:5.2.2"

**Comment by radiocity** [comment]
Would you mind to keep project documentation up to date? It is confusing.
